### PR TITLE
Add correct host url.

### PR DESCRIPTION
**Pull request by simoneduca**

### CODE REVIEW

**Comment by brian-c** [comment]
What happened here? This is an absolutely fundamental change.

@astopy has this changed, or was this the intended host all along?

**Comment by rogerhutchings** [comment]
I fucked up. It's been reverted.

**Comment by brian-c** [comment]
Ah, missed that. Panicked, sorry!

**Comment by rogerhutchings** [comment]
Nothing to apologise for, it was my bad

**Pull request merged**
