### PR TITLE
v2.12.3: Security patch

### PR DESCRIPTION
**Pull request by eatyourgreens**
This updates outdated packages, including a security fix for lodash.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
PJC doesn't have any tests for the API client itself. You have to install a pre-release version to PFE (or whichever app you want to test) in order to test it. 😞

**Comment by eatyourgreens** [comment]
That said, `json-api-client` hasn't changed and that's the bit I'd think would be most likely to break.

**Comment by rogerhutchings** [comment]
It does, but only for auth and stats 🤦‍♂

**Comment by eatyourgreens** [comment]
Dependabot should stage a PR on PFE with this patch, so we can test it that way. Not ideal, I know.

**Pull request merged**
