### PR TITLE
fix: ignore null items in API responses

### LINKED ISSUE #238: API client errors with 'data is null' for some Talk searches
https://github.com/zooniverse/panoptes-javascript-client/blob/8cd40d76d52513f6f41cfac2c8d2cdb12a092440/lib/json-api-client/index.js#L94-L97

Some Talk API searches return an array of comments that include `null` entries. Those crash here, when `resourceData` is null.

Example URL:
https://www.zooniverse.org/talk/search?page=3&query=depression

### PR DESCRIPTION
**Pull request by eatyourgreens**
- configure the talk client to use a mock API for tests.
- mock the Talk API with `nock`, using snapshots of actual API responses.
- test a talk production search that is known to break the API client.
- ignore null response data, so that the tests pass.
- fixes #238.
- fixes zooniverse/Panoptes-Front-End#7066.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
@mcbouslog this fixes a bug that Alisa found earlier this week.

**Comment by eatyourgreens** [comment]
Now with mocks, so that the tests aren't running searches against the live API. The mocks are simply JSON snapshots from real Talk searxhes, including the search that's broken.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/Panoptes-Front-End/pull/7071 installs this version of the client in PFE. 

It needs to be deployed to staging, but here's a link to one of the broken searches:

https://pr-7071.pfe-preview.zooniverse.org/talk/search?query=depression&env=production

**Review by mcbouslog — APPROVED** [review]
Changes look good, mock talkClient and testing additions look great.

Confirmed using https://github.com/zooniverse/Panoptes-Front-End/pull/7071 locally that existing error message "There was an error with your search. Please try again." is fixed with these changes 👍 . 

On page 3 of the results (https://local.zooniverse.org:3735/talk/search?env=production&page=3&query=depression) the pagination shows a page 4 and 5, which are the `null` response data pages, which is a little confusing, but that's ok and beyond the scope of these changes, just noting for myself.

**Comment by eatyourgreens** [comment]
There's definitely something weird going on with that search. After the first 29 results, the remaining 13 are all null.

**Pull request merged**
