### PR TITLE
add stats sever

### PR DESCRIPTION
**Pull request by CKrawczyk**
This adds the configuration for the stats server in preparation for the new PFE project stats page.

### CODE REVIEW

**Comment by rogerhutchings** [comment]
@CKrawczyk Does the staging url actually exist? If it's particular to your setup, it probably shouldn't be in the lib

**Comment by CKrawczyk** [comment]
@rogerhutchings I don't think so, that was just carried over form @camallen original code that I based mine off of.  I think it can be removed without any issue.

**Comment by camallen** [comment]
no staging stats site exists.

**Comment by rogerhutchings** [comment]
cool, happy to merge that once it's been taken out then

**Comment by CKrawczyk** [comment]
Should be good to go.

**Pull request merged**
