### PR TITLE
Add panoptes.zooniverse.org for OAuth

### PR DESCRIPTION
**Pull request by simoneduca**
@brian-c Did I miss anything?

### CODE REVIEW

**Comment by brian-c** [comment]
Whoa whoa whoa, sorry, I think I may have misunderstood this entire problem:

Is `oauth` is an environment-level thing?

In projects that use oauth for sign-in, do **all** API calls point to a different domain?

**Comment by eatyourgreens** [comment]
I think this should be a new `OAUTH_HOSTS` hash, with OAuth hosts for production and staging, so `OAUTH_HOSTS.production = "https://panoptes.zooniverse.org"` Then reference that, instead of `API_HOSTS` when you're setting up an OAuth URL.

**Comment by simoneduca** [comment]
Sorry @brian-c, I think I don't fully understand all the config values in there. I've started along the lines @eatyourgreens suggested (thanks!), but I'm not sure how to continue. Gonna do some reading before I'll carry on.

**Comment by simoneduca** [comment]
Hopefully this makes more sense now. I have added a separate `oauth` section. However I wasn't sure about the need of setting the host from shell, so I left it out.

**Comment by brian-c** [comment]
@simoneduca I've added a super basic manual test for oauth at examples/oauth.js (using the Wildcam Gorongosa Education app ID). I think this should work, but I can't seem to get it hooked up right. Mind taking a stab at it?

**Comment by simoneduca** [comment]
Of course, thanks. Will have a look today.

**Comment by simoneduca** [comment]
@brian-c I think what you were using wasn't the WGE app ID, but a token for the Education API that the app relies on. That token is dead now. I've added the actual WGE app ID now.
However I'm still not sure if it's working: 
screen shot 2016-03-21 at 11 32 23

The beefy app get stuck on this url https://panoptes-staging.zooniverse.org/oauth/authorize?response_type=token&client_id=442c8c4910fbb9be14bd9a92ee6e14ad29159d0217d0345fd9b2db3d881c4a7d&redirect_uri=http://127.0.0.1:9966/

Perhaps it's just because the local testing url is rejected by production server (needs whitelisting or something).

Thoughts?

**Comment by simoneduca** [comment]
@brian-c Ignore previous comment please. I've successfully got your example working. The app ID you were using wasn't the correct one. After changing that and adding the local url to Doorkeeper, all was good. No errors, let alone errors about Babel. Did you have any joy with it?

**Comment by brian-c** [comment]
Cool, works fine now. Thanks @simoneduca!

**Comment by brian-c** [comment]
Published as 2.2.0

**Comment by simoneduca** [comment]
NP, thank you @brian-c.

**Pull request merged**
