### PR TITLE
Update stats-client for user_id query

### PR DESCRIPTION
**Pull request by mcbouslog**
- updates statsClient to accept user_id, added in https://github.com/zooniverse/zoo-event-stats/pull/83
- refactors queries to data object as per [makeHTTPRequest](https://github.com/zooniverse/json-api-client/blob/master/src/make-http-request.coffee#L30)
- updates related test, though test could be improved, this client will be phased out, so didn't dive into

This functionality will allow the new [Notes from Nature Field Book](https://github.com/zooniverse/notes-from-nature-field-book) to provide user stats in a way greatly desired by the research team and volunteers.

### CODE REVIEW

**Comment by mcbouslog** [comment]
I noticed @eatyourgreens and @shaunanoordin recently updated this client, maybe could review this PR? Though no worries if not, just let me know.  Let me know if there's anything I can do to help test.

**Comment by mcbouslog** [comment]
Great suggestion @shaunanoordin regarding tests. Let me see if I can work something in within the next day or two, or if not maybe I do indeed play the expedite card. I'll update accordingly. Thanks!

**Comment by camallen** [comment]
I agree with @shaunanoordin this can do with another test but it's should work just fine by the look, noting that each of those query params are optional via the API. 

Also the `makeHTTPRequest` will transform the data object to query params which i guess is more consistent with the rest of the client library. https://github.com/zooniverse/json-api-client/blob/1a2433b28464ca37854774586d5133ebaf0be60e/src/make-http-request.coffee#L15

**Comment by camallen** [comment]
Not blocking this work - but does the tests actually hit the staging stats API? It really shouldn't be doing this in the test env, instead it should have a stubbed client that just returns fake json vs hitting the network.

**Comment by mcbouslog** [comment]
Yes I think it does actually hit the stats API, which is strange. 
It doesn't make it any less strange, but are the [auth tests](https://github.com/zooniverse/panoptes-javascript-client/blob/master/test/auth.js) as well?

Is the most efficient way to create a statsClient stub to add something like [sinon](https://sinonjs.org/releases/v7.1.1/)?
I don't think I need to add [mocha](https://mochajs.org/), but not entirely sure, might be best way to restore client after stubbing?

**Comment by camallen** [comment]
they probably do :sadpanda: 

check how PFE does it - i don't think this should stop the PR being merged either.

- https://github.com/zooniverse/Panoptes-Front-End/blob/master/test/fake-api-client.js
- https://github.com/zooniverse/Panoptes-Front-End/blob/0364030aafd651e5bbf8d436f815d96fabcd59fc/test/mock-panoptes-resource.js#L4

**Pull request merged**
